name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    name: Deploy Frontend (Next.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install yarn -g
            cd /var/www/html/Online-Gacha-Final

            # 安全な方法：GitHub の master を強制的に上書きで同期
            sudo git fetch origin
            sudo git reset --hard origin/master

            cd frontend
            yarn install
            npm run build
            pm2 restart gacha-frontend

  deploy-backend:
    name: Deploy Backend (NestJS)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/html/Online-Gacha-Final

            # 安全な方法：GitHub の master を強制的に上書きで同期
            sudo git fetch origin
            sudo git reset --hard origin/master

            cd backend
            yarn install
            npm run build
            pm2 restart gacha-backend
