name: Deploy to EC2
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy Frontend & Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            # 共通：NVM の読み込み
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # ディレクトリ移動＆最新化
            APP_DIR=/var/www/html/Online-Gacha-Final
            cd $APP_DIR
            
            # git操作（sudoなしで実行）
            git fetch origin
            git reset --hard origin/master
            
            # 権限設定（git操作の後に実行）
            echo "ディレクトリ権限を設定しています..."
            sudo chown -R $(whoami) $APP_DIR
            sudo chmod -R 755 $APP_DIR
            
            # yarn.lockファイルの権限を特別に設定
            echo "yarn.lockファイルの権限を設定しています..."
            sudo chmod 666 $APP_DIR/backend/yarn.lock || true
            sudo chmod 666 $APP_DIR/frontend/yarn.lock || true

            # ── バックエンド処理 ──
            cd $APP_DIR/backend
            # node_modulesを削除して再インストール
            echo "node_modulesを削除しています..."
            rm -rf node_modules
            
            # AWS SDKモジュールをインストール
            echo "AWS SDKモジュールをインストールしています..."
            npm install --save @aws-sdk/client-s3 @aws-sdk/s3-request-presigner --legacy-peer-deps
            
            yarn install
            echo "Building backend..."
            npm run build || echo "ビルドにエラーがありますが継続します"
            # PM2 プロセス再起動（存在しなければ起動）
            pm2 describe gacha-backend \
              && pm2 restart gacha-backend \
              || pm2 start dist/main.js --name gacha-backend

            # ── フロントエンド処理 ──
            cd $APP_DIR/frontend
            # node_modulesを削除して再インストール
            echo "node_modulesを削除しています..."
            rm -rf node_modules
            yarn install
            echo "Building frontend..."
            npm run build
            pm2 describe gacha-frontend \
              && pm2 restart gacha-frontend \
              || pm2 start npm --name gacha-frontend -- start

            # 最後にプロセス一覧を出力
            pm2 list
