name: Deploy to EC2
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy Frontend & Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            # 共通：NVM の読み込み
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            # ディレクトリ移動＆最新化
            APP_DIR=/var/www/html/Online-Gacha-Final
            
            # 権限設定（デプロイ前に実行）
            echo "ディレクトリ権限を設定しています..."
            sudo chown -R $(whoami):$(whoami) $APP_DIR || echo "権限変更に失敗しましたが続行します"
            
            cd $APP_DIR
            sudo git fetch origin
            sudo git reset --hard origin/master

            # ── バックエンド処理 ──
            cd $APP_DIR/backend
            yarn install
            echo "Building backend..."
            npm run build || echo "ビルドにエラーがありますが継続します"
            # PM2 プロセス再起動（存在しなければ起動）
            pm2 describe gacha-backend \
              && pm2 restart gacha-backend \
              || pm2 start dist/main.js --name gacha-backend

            # ── フロントエンド処理 ──
            cd $APP_DIR/frontend
            yarn install
            echo "Building frontend..."
            npm run build
            pm2 describe gacha-frontend \
              && pm2 restart gacha-frontend \
              || pm2 start npm --name gacha-frontend -- start

            # 最後にプロセス一覧を出力
            pm2 list
